In [ ]:
from integracao import *
import random

In [7]:
gen,melhor_de_todos = algoritmo_genetico(20,500,3)


GERACAO : 1
TABULEIRO INICIAL DA GERACAO
[4 6 0]
[8 7 1]
[3 5 2]

FITNESS DO TABULEIRO:  -20.0
MEDIA DA GERACAO:  -19.264
FITNESS DO MELHOR DE TODOS:  -50 INDIVIDUO : 0
MELHOR INDIVIDUO:  160  COM FITNESS:  -12.0
TABULEIRO FINAL DO MELHOR INDIVIDUO
[7 3 0]
[4 1 6]
[5 8 2]

------------------------------------------------------
[392, 208, 220, -880, 391, -785, 382, 343, 592, 663, 312, -353, 397, 261, -298, -753, -531, -632, 991, -448, -271, -976, 60, 169, 407, 243, 422, 85, 259, 907, -972, -87, -877, -446, -232, 995, 83, -422, 460, 948, 545, 651, 208, 849, 162, 297, -223, 148, -123, -733, -16, -717, -225, 55, -766, 272, 901, 288, -169, -867, -686, 60, 153, 210, 504, -963, 429, -671, -120, 146, 625, -112, 400, 715, -496, -68, -423, 290, -832, -361, -93, -163, 30, 701, -928, -762, 190, 212, 509, 492, -543, -312, -945, 556, -940, -832, 282, 207, 843, -739, -812, -249, -232, -780, -128, 912, 52, 122, -622, 173, -523, 137, -524, -887, -113, -147, -341, 582, -164, 953, 578, -705, 272, -494, -

In [22]:
print (gen.players[melhor_de_todos].DNA.vetorDNA)

vet = [0,0]
fit = 0
    #Gerar tabuleiro aleatorio para os individuos da geracao
while (fit > -16):
    numeros = list(range(3*3))
    random.shuffle(numeros)
    matriz = np.array(numeros).reshape((3, 3))
    tabuleiro = Tabuleiro(3,3,matriz)
    fit,vet = fitness(tabuleiro,vet)

#tabuleiro = Tabuleiro(3,3,matriz)
tabuleiro.printa_tabuleiro()
gen.players[melhor_de_todos].tabuleiro=tabuleiro
fit,vet = fitness(tabuleiro,vet)
print(fit)

[87.74103346870398, 51.81919599999999, 227.847, 420.4000000000001, 121.30774999999998, 51.68483331899998, 94.03099999999995, 343, 600.976, 669.478, 141.57, -187.443, 397.055, 89.82315, -298, -753, -208.8430154075, -315.84200000000004, 991, -167.26999999999995, -271, -981.844, 785.9000000000001, 169, 124.82591249999999, 98.87216499999994, 425.959, -67.88064490871999, -449.7489999999999, 56.8351219772, -300.1656, -87, 294.2170295039999, 915.5999999999999, -934.3, 636.1034999999999, 45.320049999999995, -260.577833, 456.642, 974.702, 543.365, 378.5, 216.84, 840.526, 132.6319243, 297, -890.5, 114.60379999999999, -46.494, 773.9000000000001, 926.5, -284.78705150444995, -225, -271.62899999999996, -758.383, 272, 312.9173, 142.18560000000002, -21.663197778559255, -867, -401.1385, 883.8, 53.2083, 130.791, 457.70400000000006, -964.183, -658.0, -56.10500000000005, 125.09999999999991, 974.5779999999999, 228.65625, -110.596, -540.0, 715, -496, -12.190521839999999, 40.40000000000009, -480.0, -660.9, -

In [40]:
gen.players[melhor_de_todos] = controlar_estado_jogador(gen.players[melhor_de_todos])
gen.players[melhor_de_todos].tabuleiro.printa_tabuleiro()
fit,vet = fitness(gen.players[melhor_de_todos].tabuleiro,vet)
print
print(fit)

[6 5 0]
[7 2 1]
[4 8 3]

-14.0
